name: CI

on:
  push:
    paths:
      - 'CostEstimateGenerator/**'
  pull_request:
    paths:
      - 'CostEstimateGenerator/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CostEstimateGenerator/requirements.txt
          pip install -e CostEstimateGenerator
      - name: Run tests
        run: python -m pytest -q
        working-directory: CostEstimateGenerator
